### ISSUE TITLE
您好，关于论文中的TABLE IV ！

### ISSUE THREAD

**Issue by FreshmanMa** [HwangBo94/Anti-UAV410#27]
”All re-trained trackers retain default settings and default pre-training weights, the experimental results are shown in Table IV” 想问下，是将Anti-uav410 train 加入到LaSOT，COCO，TrackingNet, GOT-10k、 imagenetVID 这些通用目标数据集中 训练呢？ 还是单独在Anti-uav410 train 上重新训练？ 我理解的是第一种，这个数据集的比例该怎么给呢？ pytracking中的配置文件按照下面写？ 详细的训练过程能否提供下？ 目前遇到一些问题
``` 
DATASETS_NAME:
    - GOT10K_vottrain
    - LASOT
    - COCO17
    - TRACKINGNET
    - AntiUAV_train410
    DATASETS_RATIO:
    - 1
    - 1
    - 1
    - 1
    - 1
    SAMPLE_PER_EPOCH: 60000
```
